FROM node:18 AS build

WORKDIR /app

COPY /Users/upendraverma/Desktop/docker/crud-dd-task-mean-app/frontend/package*.json  ./

RUN npm install

COPY /Users/upendraverma/Desktop/docker/crud-dd-task-mean-app/frontend/  .

RUN npm run build -- --configuration production


FROM nginx:alpine

COPY default.conf  /etc/nginx/conf.d/default.conf

COPY --from=build  /app/dist/angular-15-crud/ /usr/share/nginx/html/

